imports:
    - { resource: 'nette-php70.yml' }

services:
    Sunfox\CodingStandard\Fixer\ClassNotation\ClassAndTraitVisibilityRequiredFixer:
        elements: [const, property, method]

    # short list() syntax []
    PhpCsFixer\Fixer\ListNotation\ListSyntaxFixer:
        syntax: short
